# Generated by Django 5.0.6 on 2024-11-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_proveedor_rol_rubro_servicio_tipoinforme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_servicio',
        ),
    ]
