# Generated by Django 5.0.6 on 2024-12-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_reserva_fecha_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
